[colors]
# semitransparent background 99: alpha 0.6
# cc: alpha 0.8, ff: alpha 1.0
background=0b0e14ff
text=b3b1adff
prompt=aad94cff
placeholder=3e4b59ff
input=657b83ff
match=ff8f40ff
# match=e6b450ff
selection=151b23ff
# selection=e6b450ff
selection-text=e6b450ff
# selection-text=0b0e14ff
selection-match=e6b450ff
counter=a37accff
# border=f9e2afff
border=636a72ff
