[colors]
# semitransparent background 99: alpha 0.6
# cc: alpha 0.8, ff: alpha 1.0
background=121317ff
text=b3b1adff
prompt=fab387ff
placeholder=3e4b59ff
input=657b83ff
match=ddddddff
# match=b3b1adff
selection=151b23ff
# selection=f9e2af99
selection-text=adc6ffff
# selection-text=0b0e14ff
selection-match=adc6ffff
counter=f9e2afff
border=b4befedd
# border=51595fff
